# Generated by Django 6.0.2 on 2026-03-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_codesnippet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
