# Generated by Django 6.0.3 on 2026-03-23 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_codecomment_codelike_useranswer_userprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('points_required', models.IntegerField(default=0)),
                ('questions_required', models.IntegerField(default=0)),
                ('streak_required', models.IntegerField(default=0)),
                ('codes_required', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('participants', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('questions_solved', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('codes_written', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='QuestionHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_text', models.TextField()),
                ('hint_number', models.IntegerField(default=1)),
                ('points_cost', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['hint_number'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('questions_solved', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('mastery_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='solution_code',
            field=models.TextField(blank=True, help_text='Solution code for the question'),
        ),
        migrations.AddField(
            model_name='question',
            name='solution_explanation',
            field=models.TextField(blank=True, help_text='Detailed solution explanation'),
        ),
        migrations.AddField(
            model_name='question',
            name='solved_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_topic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('general', 'General'), ('arrays', 'Arrays'), ('strings', 'Strings'), ('linked_list', 'Linked List'), ('trees', 'Trees'), ('graphs', 'Graphs'), ('dynamic_programming', 'Dynamic Programming'), ('sorting', 'Sorting'), ('searching', 'Searching'), ('recursion', 'Recursion'), ('oop', 'Object Oriented Programming'), ('functions', 'Functions'), ('loops', 'Loops'), ('conditionals', 'Conditionals')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='video_link',
            field=models.URLField(blank=True, help_text='YouTube video link for solution'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic'], name='myapp_quest_topic_e2c46a_idx'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='myapp.question'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionhint',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='myapp.question'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='myapp.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchallengeprogress',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='myapp.dailychallenge'),
        ),
        migrations.AddField(
            model_name='userchallengeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertopicprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='questionhint',
            unique_together={('question', 'hint_number')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AlterUniqueTogether(
            name='userchallengeprogress',
            unique_together={('user', 'challenge')},
        ),
        migrations.AlterUniqueTogether(
            name='usertopicprogress',
            unique_together={('user', 'topic')},
        ),
    ]
